---
- include: copy_tools.yml

- include: cleanup_containers.yml

- include: cleanup_images.yml

# contrail_additions: Cleanup Contrail Images
- include: cleanup_contrail.yml

- include: cleanup_host.yml
